### ISSUE TITLE
The Road Ahead

### ISSUE THREAD

**Issue by shnupta** [shnupta/bric#67]
Hi guys,

The project has recently had a fair bit of growth (far more than I ever expected) and so I thought it would be a good idea to address some things to help everyone with development on the project.

I haven't really done much with bric for some time now having started college this year and been pretty busy with life in general, but it's great to see so many people getting involved (and kind of makes my life easier). All the new features and improvements that are being put forward are all extremely good and are really helping the editor progress.

However, as you'll probably know - if you have worked on the editor (on the vim-change branch) - the main code is quite a mess. We've started to separate some code into features but the main bric.c file is very cluttered and unorganised.

It would be great if the main focus over the next period of development could be on organising the code into separate files and components in order to make the editor easier and more friendly to work on.

So what would really help is if this thread could be full of comments and suggestions as to how we should refactor the editor into components and sub-components (e.g. core, movement etc.). I'd love for as many people to get involved and share their ideas as this should speed up the process.

The aim being that after the code has been organised and the editor is all working. We should be able to write a small amount of basic documentation on usage of the editor and also what the sub-components do so it is easier for new developers to get started. 

Once this has happened we will use the master branch for stable code and then a beta and also development branch for new features and testing to be done.

Sorry for such a long message but I hope this will get a conversation going and help the progression of the editor before it becomes too much of a mess.

Thanks,
Casey

**Comment by shnupta** [comment]
I'm also going to be writing a contributing guide too.

**Comment by bleepcord** [comment]
Contribution guide would be a *great* idea. Also include style guidelines because I've noticed some mixed tabs and spaces that I would love to clean up :) I'm even willing to take care of it once we have a style guide. Unless you decide to use a beautifier.

I also think @doztrock's plan is perfectly reasonable. I would only add that in my opinion it's preferable to have a header file for each .c file (within reason). It would prevent `bric.h` from becoming cluttered and it would organize prototypes, enums, etc. based on their relevant implementations.

I also do not think forcing a specific editor for development of bric is a good idea. It would deter future contributors. We can use an alternative code beautifier if it's really desired. Perhaps [Uncrustify](http://uncrustify.sourceforge.net/)?

**Comment by shnupta** [comment]
HI @doztrock and @bleepcord ,

I think once #69 has been merged I will merge the vim-change branch to the master and we shall start the refactor and development moving forward from there.

I agree with @bleepcord's suggestion that we shouldn't be editor specific simply to allow new contributors to get involved without much hassle. 

I also think we should separate into header files too although this will require a bit more thought than separating the source files as code from bric.h is used in a lot of places. We will probably have to discuss the splitting up of the header file in a separate issue. 

@doztrock's examples for different source files seems like a good idea to get started.

@bleepcord I'll check out Uncrustify a bit more in a couple days and see whether it may be a good fit or not.

Thank you both very much!

**Comment by shnupta** [comment]
I would advise everyone to keep checking the projects board (link above) to see what issues and bugs need to be worked on.

**Comment by anfly0** [comment]
On the "style guidelines" topic:
I stumbled across this: https://users.ece.cmu.edu/~eno/coding/CCodingStandard.html
At least parts of it could serve as a basis for both style guidelines and a more general coding standard.
In any case it's a good read for anyone that want's to revisit some of the "old truths" regarding good C-code practices.

**Comment by andy5995** [comment]
Well there are many [coding styles](https://en.wikipedia.org/wiki/Indentation_style) to choose from. I usually go with [GNU](https://www.gnu.org/prep/standards/html_node/Formatting.html#Formatting) because I've been a GNU Linux user for so many years. And sometimes I use [indent](https://packages.debian.org/wheezy/indent) to auto-format, and it has options to format using different styles, such as K&R and GNU.

But yes, I agree one must be decided upon.

**Comment by shnupta** [comment]
K&R is probably my preferred style but that doesn't say it has to be that. When I have a spare moment I'll run the source through indent and see how it comes out.

It will also be worth checking that the naming of variables and functions is consistent (I highly doubt I paid much attention to that when I wrote it.... bad me 2 years ago)

**Comment by andy5995** [comment]
Also I'd suggest a maximum line length of 80, but making exceptions for lines up to 100. I think `indent` does that automatically. Makes the code easier to read.

As for indenting, I typically use 2 spaces not 4. That helps keep the width of the lines down when there are many nested code blocks.

And I do prefer spaces not tabs these days, because it renders on GitHub diffs more accurately.

**Comment by andy5995** [comment]
>I'm also going to be writing a contributing guide too.

This is now done

https://github.com/shnupta/bric/blob/master/CONTRIBUTING.md

> Also include style guidelines because I've noticed some mixed tabs and spaces that I would love to clean up :)

All spaces now, @bleepcord :)

>I'm even willing to take care of it once we have a style guide. Unless you decide to use a beautifier.

We did. :) That type of change is usually best left to maintainers. What happens is that when the changes are reviewed, the diff file can be over 1000 lines so it's much easier to "review" if it's only done by one or 2 people.

Anyone is still welcome to leave feedback about the new code format. I'll leave this issue closed (Casey has appointed me to help him be a co-maintainer until he has more free time), but if there's anything specific related to this ticket that still needs to be addressed, let's open individual tickets for that.

Thanks to everyone for participating in this discussion. We hope we covered all the main points with recent commits. Everything is now on the master branch and we will be deprecating the development and testing branch.

**Comment by andy5995** [comment]
I forgot to mention that Casey has started a [bric chat room](https://join.slack.com/t/bric-editor/shared_invite/enQtNDIyNjg5NzY2MTQ1LTk4OTE4ZjdiMGFmMDlhNWM2ZWJkMmM0MGQxMjNhODJlOWY1MjQzMmQ5MDEzOGM3YjM0YTJiZTc3MWY5MGNmZjI). All are welcome to join, regardless of contribution level.
