### ISSUE TITLE
Correct Makefile

### ISSUE THREAD

**Issue by shnupta** [shnupta/bric#73]
The Makefile is a bit of a hack at the moment.

We should properly organise the list of dependent source files and also use the correct install command.

**Comment by doztrock** [comment]
Hey @shnupta today I was looking for some good practices for Makefiles, and I've written this:

https://github.com/shnupta/bric/pull/79/commits/6afdb9c928efde83c6104a7c76028ef295622f5f

Now we don't need to edit the former `$DEPENDENCIES` variable to add new objects in the compilation command.

Also I've document the files, with some comments about the process.

Please could you check it and if you have any question I'am available to answer.

I've made this commit in my `vim-change` branch, so If you accept them there are included in the pull request I've made.

Regards

**Comment by shnupta** [comment]
Hi @doztrock ,

I really like your documentation in the code that you did in your commit. As you will see I've requested that you make a separate PR for the Makefile changes so we can discuss more on this thread about what standard we should apply to our Makefile. 

I think that building recursively sounds like a good idea, would you be able to provide some links to research you've done?

Thanks

**Comment by doztrock** [comment]
@shnupta I've separated the pull request now, give me some minutes and i'll post some refereneces i've used to build my Makefile.

**Comment by doztrock** [comment]
@shnupta Did you delete the vim-change branch?

**Comment by shnupta** [comment]
@doztrock Yes the old vim-change branch has been merged into master.

**Comment by doztrock** [comment]
First of all, I've check this [document](https://github.com/luarocks/luarocks/wiki/Recommended-practices-for-Makefiles) about some good practices for Makefiles.

They talk about the useing of variables into the Makefile, for everything, it make it more readable and changeable in some cases.

Also, I've read this [StackOverflow Question](https://stackoverflow.com/questions/2826029/passing-additional-variables-from-command-line-to-make) to learn more about the passing of variable between child Makefiles.

They talk about the using of `export` command used to pass global variable to some child Makefiles, I'm using it to set the `CC` and `CFLAGS` variables trough the main Makefile and childs.

Finally I've found [this question](https://stackoverflow.com/questions/14589614/make-recursive-all-c-files) about, how to compile all *c source file recursivelly, I've added some modifications I've used in other C project.

That's my tiny research I've made.

Here my Makefile propositions:

[Main Makefile](https://github.com/doztrock/bric/blob/development/Makefile)
[Child Makefile](https://github.com/doztrock/bric/blob/development/src/Makefile)

You are able to download my development branch and test it on the [commit](https://github.com/doztrock/bric/commit/6afdb9c928efde83c6104a7c76028ef295622f5f), don't use the HEAD because I'm trying to add a new change, so you would get some errors.

Regards!

**Comment by andy5995** [comment]
I can add an autoconf and automake file, which should make things easier to manage in the long-term.

**Comment by shnupta** [comment]
Going to close this as the recent PR #119 by @andy5995 has changed the way we use Makefiles so this issue is no longer up to date.
