### ISSUE TITLE
Test new undo function

### ISSUE THREAD

**Issue by shnupta** [shnupta/bric#98]
Hi there everyone,

If possible could we get some people to test this new PR #90 on @DreamTheater2016 's development branch and comment your results back here please.

Many thanks! :)

**Comment by gaurav-git** [comment]
@shnupta I tested the PR #90 on my machine `4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`. The undo functionality is working fine.

One thing I observed that if say user deletes previous line and writes a new line having more characters than the previous one and then presses CTRL+Z then the old line do gets back but the cursor maintains the last position i.e. at the end of the longest string which gets deleted when user presses CTRL+Z.

Otherwise, the undo functionality is working fine and I didn't get any segfault in the process of undoing.

**Comment by shnupta** [comment]
Hmm weird, as soon as I use undo it segfaults straight away. How did you build the executable @gaurav-git ?

<img width="575" alt="screen shot 2017-12-29 at 12 14 53" src="https://user-images.githubusercontent.com/16493023/34436924-0af99418-ec92-11e7-963f-cf9dc3019cfd.png">

**Comment by gaurav-git** [comment]
I just executed `make`.
```
make --directory=src
make[1]: Entering directory '/home/gaurav/OpenSource/bric-undo/bric/src'
gcc -c locking.c -o locking.o -g
gcc -c bric.c -o bric.o -g
gcc -c tagstack.c -o tagstack.o -g
gcc -c handling.c -o handling.o -g
make[1]: Leaving directory '/home/gaurav/OpenSource/bric-undo/bric/src'
gcc src/*.o -Wall -g -W -pedantic -std=gnu99 -lm -o bric -g
```

And this is my gcc version:

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.5' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
```

**Comment by Rhitabrat** [comment]
@shnupta I am using ArchLinux. I am not getting any segfaults.
But, as mentioned by @gaurav-git , the cursor remains at the same position where it was before pressing Ctrl-Z ie. if the cursor is at the 3rd column of a row before pressing Ctrl-Z, it remains at the same position(3rd column) even after pressing Ctrl-Z. Otherwise, it is working fine.

**Comment by shnupta** [comment]
Hmm weird, I still have the segfault whenever I try to undo. Please could one of you try opening bric.c using 'dr' in normal mode to delete the first row (without moving the cursor), tell me what happens  and then try to undo this. When I delete the first row I get some other part of the file appearing.

I have a feeling this issue must just be specific to do with macOS is all your Linux systems are working perfectly, except for the cursor issue. I'll try on my Linux build later and update this comment.

**Comment by Rhitabrat** [comment]
The undo function is working fine. I am not getting any error.

**Comment by partytime** [comment]
@shnupta did you cherry pick commit bfcaaecc532d68610554c4a2baf37fac24a738e8  ? I haven't had a segfault after that patch

**Comment by anfly0** [comment]
@shnupta I have the same problem with `dr` and undo in normal mode. 
The problem seems to be that when `editor_update_row()` is called from `process_undo()` after a `dr`, 
the value of `row->size` passed to `editor_update_row()` can be negative.
This in turn causes the first call to `malloc` in `editor_update_row()` to fail, which in turn causes a segfault later on.
@DreamTheater2016 Do you have any thoughts on this?

**Comment by anfly0** [comment]
Well I don't want to step on anyone's toes, but if no one is working on this then it might be time to close this issue and open a new one with a feature request for the "undo functionality". This would perhaps give new developers (like myself) a nice challenge, and keep the project a bit more lively. Just a thought.

**Comment by shnupta** [comment]
Not at all. I think your suggestion is probably the best thing to do.
